# GitHub Pages config

title: Simple HTTP(S) Server
description: Simple server to run local browser tests.
author:
  name: © TypeScriptLibs and Contributors
  email: bug@typescriptlibs.org

header_pages:
  - www/downloads.md
  - SECURITY.md
  - LICENSE.md
  - www/all-libraries.md

include:
  - LICENSE.md
  - README.md
  - SECURITY.md
  - www/all-libraries.md
  - www/downloads.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

remote_theme: jekyll/minima

minima:
  date_format: "%Y-%m-%d"
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/typescriptlibs/" }
    - { platform: rss,  user_url: "feed.xml" }

show_excerpts: false

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
