#!/usr/bin/env perl
# Taken from https://en.wikipedia.org/wiki/Common_Gateway_Interface#Example

=head1 DESCRIPTION

printenv — a CGI program that just prints its environment

=cut
print "Content-Type: text/plain\n\n";

foreach ( sort keys %ENV ) {
    print "$_=\"$ENV{$_}\"\n";
}
